-- Retail Data Warehouse
-- Snowflake database and schemas

CREATE DATABASE IF NOT EXISTS RETAIL_DW;

USE DATABASE RETAIL_DW;

CREATE SCHEMA IF NOT EXISTS RAW;

CREATE SCHEMA IF NOT EXISTS STAGING;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;